package com.AllanCleiton.entidades;

public class HtmlTelas {
	
	public String TelaCadastro() {
		String telaCadastro = "<!DOCTYPE html>\r\n"
				+ "    <html lang=\"pt-br\">\r\n"
				+ "    <head>\r\n"
				+ "        <meta charset=\"UTF-8\">\r\n"
				+ "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "        <title>Cadastro de usuário</title>\r\n"
				+ "        <link rel=\"stylesheet\" href=\"style.css\">\r\n"
				+ "        <link rel=\"stylesheet\" href=\"stylefrm.css\">\r\n"
				+ "    </head>\r\n"
				+ "    \r\n"
				+ "    <body>\r\n"
				+ "        <header>\r\n"
				+ "            <a href=\"#\">HOME</a>\r\n"
				+ "            <a href=\"frmusuario.html\">CADASTRAR</a>\r\n"
				+ "            <a href=\"frmaltusuario.html\">ALTERAR</a>\r\n"
				+ "            <a href=\"frmbuscarusuario.html\">PESQUISAR</a>\r\n"
				+ "            <a href=\"#\">EXCLUIR</a>\r\n"
				+ "            \r\n"
				+ "        </header>\r\n"
				+ "    \r\n"
				+ "        <form action=\"usucontroller.do\" method=\"post\" autocomplete=\"off\">\r\n"
				+ "            <h1 style=\"color: aliceblue;\">Cadastrar usuario</h1>\r\n"
				+ "            \r\n"
				+ "            <div id=\"div01\">\r\n"
				+ "                <div id=\"divL\">\r\n"
				+ "                    <label style=\"color: aliceblue;\">Nome: </label>\r\n"
				+ "                    <label style=\"color: aliceblue;\">Login: </label>\r\n"
				+ "                    <label style=\"color: aliceblue;\">Senha: </label>\r\n"
				+ "                </div>\r\n"
				+ "                <div>\r\n"
				+ "                    <input type=\"text\" name=\"txtnome\" value=\"\">\r\n"
				+ "                    <input type=\"text\" name=\"txtlogin\" value=\"\">\r\n"
				+ "                    <input type=\"password\" name=\"txtsenha\" value=\"\" maxlength=\"6\">\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "            \r\n"
				+ "            <div id=\"sub01\"><input type=\"submit\" name=\"btnsubmit\" value=\"Cadastrar\" id=\"sub02\"></div>\r\n"
				+ "        </form>\r\n"
				+ "    </body>\r\n"
				+ "    \r\n"
				+ "    </html>";
		return telaCadastro;
	}
	
	public String TelaAlterar() {
		String telaAlterar = "<!DOCTYPE html>\r\n"
				+ "    <html lang=\"pt-br\">\r\n"
				+ "    <head>\r\n"
				+ "        <meta charset=\"UTF-8\">\r\n"
				+ "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "        <title>Alterar usuário</title>\r\n"
				+ "        <link rel=\"stylesheet\" href=\"style.css\">\r\n"
				+ "        <link rel=\"stylesheet\" href=\"stylefrm.css\">\r\n"
				+ "    </head>\r\n"
				+ "    \r\n"
				+ "    <body>\r\n"
				+ "        <header>\r\n"
				+ "            <a href=\"#\">HOME</a>\r\n"
				+ "            <a href=\"frmusuario.html\">CADASTRAR</a>\r\n"
				+ "            <a href=\"frmaltusuario.html\">ALTERAR</a>\r\n"
				+ "            <a href=\"frmbuscarusuario.html\">PESQUISAR</a>\r\n"
				+ "            <a href=\"#\">EXCLUIR</a>\r\n"
				+ "        </header>\r\n"
				+ "    \r\n"
				+ "        <form action=\"usucontroller.do\" method=\"post\" autocomplete=\"off\">\r\n"
				+ "            <h1 style=\"color: aliceblue;\">Alterar usuario</h1>\r\n"
				+ "            \r\n"
				+ "            <div id=\"div01\">\r\n"
				+ "                <div id=\"divL\">\r\n"
				+ "                    <label style=\"color: aliceblue;\">ID: </label>\r\n"
				+ "                    <label style=\"color: aliceblue;\">Nome: </label>\r\n"
				+ "                    <label style=\"color: aliceblue;\">Login: </label>\r\n"
				+ "                    <label style=\"color: aliceblue;\">Senha: </label>\r\n"
				+ "                </div>\r\n"
				+ "                <div>\r\n"
				+ "                    <input type=\"text\" name=\"txtid\" value=\"\">\r\n"
				+ "                    <input type=\"text\" name=\"txtnome\" value=\"\">\r\n"
				+ "                    <input type=\"text\" name=\"txtlogin\" value=\"\">\r\n"
				+ "                    <input type=\"password\" name=\"txtsenha\" value=\"\" maxlength=\"6\">\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "            \r\n"
				+ "            <div id=\"sub01\"><input type=\"submit\" name=\"btnsubmit\" value=\"Alterar\" id=\"sub02\" ></div>\r\n"
				+ "        </form>\r\n"
				+ "\r\n"
				+ "    </body>\r\n"
				+ "    \r\n"
				+ "    </html>";
		return telaAlterar;
	}
	
	public String Inicio_Tabela() {

		String inicio_Tabela = "<!DOCTYPE html>\r\n"
				+ "    <html lang=\"pt-br\">\r\n"
				+ "    <head>\r\n"
				+ "        <meta charset=\"UTF-8\">\r\n"
				+ "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "        <title>Buscar usuários</title>\r\n"
				+ "        <link rel=\"stylesheet\" href=\"style.css\">\r\n"
				+ "        \r\n"
				+ "        <style>\r\n"
				+ "            body{\r\n"
				+ "                font-family: Arial, Helvetica, sans-serif;\r\n"
				+ "                \r\n"
				+ "            }\r\n"
				+ "            table{\r\n"
				+ "                width: 400px;\r\n"
				+ "                border-collapse: collapse;\r\n"
				+ "                margin: auto;\r\n"
				+ "            }\r\n"
				+ "            thead{\r\n"
				+ "                background-color: rgba(81, 167, 236, 0.842);\r\n"
				+ "                border-bottom: 2px solid black;\r\n"
				+ "            }\r\n"
				+ "            .coluna{\r\n"
				+ "                background-color: rgba(204, 248, 248, 0.822);\r\n"
				+ "                \r\n"
				+ "            }\r\n"
				+ "            .coluna2{\r\n"
				+ "                background-color: rgb(248, 241, 232);\r\n"
				+ "                \r\n"
				+ "            }\r\n"
				+ "            td{\r\n"
				+ "                border: 1px solid black;\r\n"
				+ "                padding: 8px;\r\n"
				+ "                border-right: 2px solid black;\r\n"
				+ "                \r\n"
				+ "            }\r\n"
				+ "            th{\r\n"
				+ "                border: 1px solid black;\r\n"
				+ "                padding: 5px;\r\n"
				+ "                border-right: 2px solid black;\r\n"
				+ "                \r\n"
				+ "            }\r\n"
				+ "        </style>\r\n"
				+ "    </head>\r\n"
				+ "\r\n"
				+ "    <body>\r\n"
				+ "        <header>\r\n"
				+ "            <a href=\"#\">HOME</a>\r\n"
				+ "            <a href=\"frmusuario.html\">CADASTRAR</a>\r\n"
				+ "            <a href=\"frmaltusuario.html\">ALTERAR</a>\r\n"
				+ "            <a href=\"frmexcluirusuario.html\">EXCLUIR</a>\r\n"
				+ "            <form action=\"usucontroller.do\" method=\"get\"><input style=\"background-color: rgb(78, 151, 151);\r\n"
				+ "                height: 50px;\r\n"
				+ "                width: 100px;\r\n"
				+ "                margin: 10px;\r\n"
				+ "                display: flex;\r\n"
				+ "                align-items: center;\r\n"
				+ "                padding: 10px;\r\n"
				+ "                text-decoration: none;\r\n"
				+ "                color: aliceblue;\" type=\"submit\" value=\"Buscar\"></form>\r\n"
				+ "            \r\n"
				+ "        </header>\r\n"
				+ "        <table>\r\n"
				+ "            <thead>\r\n"
				+ "                <tr>\r\n"
				+ "                    <th >ID</th>\r\n"
				+ "                    <th >NOME</th>\r\n"
				+ "                    <th >lOGIN</th>\r\n"
				+ "                </tr>\r\n"
				+ "            </thead>\r\n"
				+ "            <tbody>";
		return inicio_Tabela;
	}

	public String Fim_Tabela() {
		String fim_Tabela = "</tbody></table></body>\r\n"
				+ "    \r\n"
				+ "    </html>";
		return fim_Tabela;
	}

}
